ElYusubov/AWESOME-Azure-Bicep

- README.md
- Added 3 articles from community blogs related to Azure Bicep
> Added Community Articals Related to Bicep

- README.md
Add bicep video, blog and tool resources I have created.
> Add resources from samcogan.com

- README.md
Infrastructure as Code with Azure Bicep
> Added Community Book

- README.md
Added 'Bicep Testing Framework (BenchPress)'
> Added 'Bicep Testing Framework (BenchPress)'

- README.md
- Added 'Azure Bicep lambdas expressions' blog
- Updated my blog URLs
> Added blog about Bicep lambdas and updated urls

- README.md
Added my blog about deployment scripts.
> Added blog about deployment scripts

- README.md
> Added CARML acronym

- README.md
Add in links to videos and blogs I have written about Azure Bicep
> Add video and blogs

- README.md
Fixed dead markdown links as stated in the error of the workflow run: https://github.com/ElYusubov/AWESOME-Azure-Bicep/actions/runs/4552181987/jobs/8027200293
> Fixed dead markdown links

- README.md
@ElYusubov The "EP7: Getting Started with Azure Bicep" podcast has been removed from all podcast platforms. His YouTube video is still online (which is informative!), so added this to the list instead.
> Removed deadlink, added community Bicep video

- README.md
Fix not working anchor links (Back To Top) in README.
> Fix not working anchor links

- README.md
Added a repository to the list of community repositories where I store bicep-snippets that I frequently use and share.
> Added johnlokerse/bicep-snippets community repo

- README.md
Added my latest blog post about "Subnetting in Azure Bicep"
> Added blog 'Subnetting in Azure Bicep'

- README.md
Added new repository entry for my Bicep project Bicepify where others can break down concepts with easy to understand demo examples & documentation to compliment.
> Adding 1x community repo 

- README.md
Added my latest blog on how to use environment variables in Azure Bicep.
> Added blog 'Work with environment variables in Azure Bicep'

- README.md
I added the url to my side project for a cheat sheet on Azure Bicep. Hope it helps someone!
> Added Azure Bicep Cheat Sheet link

- README.md
Added my latest blog on User-Defined Types in Azure Bicep
> Added 'Enhance objects with User-Defined Types in Azure Bicep' blog

- README.md
Added 1x community Bicep article - "Seamlessly deploy Azure Front Door Premium with Private Endpoint to App Services"
Added 1x community forum URL - Azure Bicep subreddit forum/discussion
> Adding 1x community article + 1x community forum 

- README.md
Happy new year! Wish you all the best. 
Updated URL of blog from @lukemurraynz
> Updated URL to fix failing action

- README.md
Added my latest blog
Also PR number 100! ;-)
> Added blog: Reusability with export and import in Azure Bicep

- README.md
Adding Azure Verified Modules (AVM) which runs under https://github.com/Azure/bicep-registry-modules/tree/main/avm. More details can be found at https://aka.ms/avm.
> Adding Azure Verified Modules (AVM)

- README.md
Adding community tool https://github.com/Azure4DevOps/check-azure-bicep
> Adding the Check-Azure-Bicep community tool

- .github/workflows/mlc_config.json
> Updated markdown link checker config

- README.md
Added blog: Create your own function in Azure Bicep with user-defined functions
> Added blog on user-defined functions

- README.md
added 1x community repo. for bicep-docs.
I meant to add this into my last PR. Sorry about that guys! :)
> 1x community repo

- README.md
Azure Update Manager Accelerator written using Azure Bicep, link added to README.md
> Adding Azure Update Manager Accelerator GitHub repo

- README.md
- Added Azure Bicep users LinkedIn community (by @riosengineer and me)
- Added my latest blog on improving code generation with custom instructions for GitHub Copilot - with examples on how to use it with Azure Bicep
> Added Azure Bicep users group and 1x blog

- README.md
Control your Azure Bicep deployment flow with the fail function
> Added 1x blog on fail function

- README.md
1x Added Community Article link
Azure Deployment Stacks: Zero to Hero 🦾❤️
> 1x Add Community Article

- README.md
I added links to couple of articles from my blog, a video from community events (where I spoke), `az-bootstrap` tool from [Stu Mace](https://github.com/kewalaka), and a website/repo for a hands-on workshop with labs (from Infrastructure as Code User Group Oslo that I co-organize)
> Add articles and videos from myself and IaC UG Oslo
